name: property_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  intl: ^0.19.0
  simple_circular_progress_bar: ^1.0.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  clean_architecture_with_state_management: ^1.1.2
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/navbar/active/
    - assets/icons/navbar/nonactive/
    - assets/images/
    - assets/api/

  fonts:
    # Outfit
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    
    # Rubik
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    
    # Lexend
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
